name: Azure Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      # Step 4: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ds2024registry.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      
      # Step 5: Build and push all Docker images using docker-compose
      - name: Build and push Docker images
        run: |
          # Build images using docker-compose and tag with "latest"
          ls /home/runner/work/ds2024_30641_constantin_andreibogdan_assignment_3/ds2024_30641_constantin_andreibogdan_assignment_3
          docker-compose up -d --no-cache

          # Tag the images with the correct registry and push them
          docker tag ds2024_30641_constantin_andreibogdan_assignment_3-chat-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-chat-service:latest
          docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-chat-service:latest

          docker tag ds2024_30641_constantin_andreibogdan_assignment_3-users-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-users-service:latest
          docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-users-service:latest

          docker tag ds2024_30641_constantin_andreibogdan_assignment_3-react-app:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-react-app:latest
          docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-react-app:latest

          docker tag ds2024_30641_constantin_andreibogdan_assignment_3-devices-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-devices-service:latest
          docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-devices-service:latest

          docker tag ds2024_30641_constantin_andreibogdan_assignment_3-monitorng-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-monitorng-service:latest
          docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3-monitorng-service:latest
