name: Azure Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      # Step 4: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ds2024registry.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
      
      # Step 5: Build and push all Docker images using docker-compose
      - name: Build and push Docker images
        run: |
          # Build images using docker-compose and tag with "latest"
          # docker-compose build --no-cache

          # docker images

          # # Tag the images with the correct registry and push them
          # docker tag ds2024_30641_constantin_andreibogdan_assignment_3_chat-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_chat-service:latest
          # docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_chat-service:latest

          # docker tag ds2024_30641_constantin_andreibogdan_assignment_3_users-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_users-service:latest
          # docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_users-service:latest

          # docker tag ds2024_30641_constantin_andreibogdan_assignment_3_react-app:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_react-app:latest
          # docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_react-app:latest

          # docker tag ds2024_30641_constantin_andreibogdan_assignment_3_devices-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_devices-service:latest
          # docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_devices-service:latest

          # docker tag ds2024_30641_constantin_andreibogdan_assignment_3_monitoring-service:latest ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_monitoring-service:latest
          # docker push ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_monitoring-service:latest
      
      # Step 6: Deploy to Azure VM
      - name: Deploy to Azure VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          scp -o StrictHostKeyChecking=no -i private_key.pem /home/runner/work/ds2024_30641_constantin_andreibogdan_assignment_3/ds2024_30641_constantin_andreibogdan_assignment_3/docker-compose-vm.yml ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:/home/${{ secrets.VM_USERNAME }}

          scp -o StrictHostKeyChecking=no -i private_key.pem /home/runner/work/ds2024_30641_constantin_andreibogdan_assignment_3/ds2024_30641_constantin_andreibogdan_assignment_3/frontend-sd/nginx.conf ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:/etc/nginx/conf.d/default.conf
          scp -o StrictHostKeyChecking=no -i private_key.pem /home/runner/work/ds2024_30641_constantin_andreibogdan_assignment_3/ds2024_30641_constantin_andreibogdan_assignment_3/frontend-sd/ssl/nginx.crt ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:/etc/ssl/certs/nginx.crt
          scp -o StrictHostKeyChecking=no -i private_key.pem /home/runner/work/ds2024_30641_constantin_andreibogdan_assignment_3/ds2024_30641_constantin_andreibogdan_assignment_3/frontend-sd/ssl/nginx.key ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:/etc/ssl/private/nginx.key

          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
            # Log in to Azure Container Registry
            az acr login --name ds2024registry --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

            # Pull latest images
            docker pull ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_chat-service:latest
            docker pull ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_users-service:latest
            docker pull ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_react-app:latest
            docker pull ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_devices-service:latest
            docker pull ds2024registry.azurecr.io/ds2024_30641_constantin_andreibogdan_assignment_3_monitoring-service:latest

            docker ps -q | xargs -r docker stop

            ls -l

            cd /home/${{ secrets.VM_USERNAME }}
            mv docker-compose-vm.yml docker-compose.yml
            # docker-compose down -v --remove-orphans
            docker-compose up -d --build --force-recreate --remove-orphans

            # Restart services with docker-compose
            # docker run -d ds2024_30641_constantin_andreibogdan_assignment_3_chat-service:latest
            # docker run -d ds2024_30641_constantin_andreibogdan_assignment_3_users-service:latest
            # docker run -d ds2024_30641_constantin_andreibogdan_assignment_3_react-app:latest
            # docker run -d ds2024_30641_constantin_andreibogdan_assignment_3_devices-service:latest
            # docker run -d ds2024_30641_constantin_andreibogdan_assignment_3_monitoring-service:latest
          EOF
